ALTER TABLE role ADD COLUMN type TEXT NOT NULL DEFAULT 'UPDATE_ME';
UPDATE ROLE SET type = 'STAFF' WHERE code = 'STAFF';
UPDATE ROLE SET type = 'CUSTOMER' WHERE code = 'CUSTOMER';
ALTER TABLE role ALTER COLUMN type DROP DEFAULT;