DELETE FROM folder;
ALTER TABLE query DROP COLUMN folder;
ALTER TABLE query ADD COLUMN folder_id INTEGER REFERENCES folder (id) ON DELETE SET NULL;
ALTER TABLE folder DROP COLUMN position;
ALTER TABLE folder DROP COLUMN code;